web:
    build: .
    volumes:
        - .:/var/www/skills-api
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/skills-api
    expose:
        - "9000"
    links:
        - db
nginx:
    image: nginx:1.9
    volumes_from:
        - web
    links:
        - web
    ports:
        - "80:80"
db:
    image: mongo:3.2
    ports:
        - "27017:27017"
    volumes:
        - /mnt/sda1/var/lib/skills-api:/data/db
