skill_create:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\CreateController

skill_read:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\ReadController

skill_delete:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\DeleteController

resource_create:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\Resources\CreateController

resource_remove:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\Resources\DeleteController

resource_vote_create:
    type:     rest
    prefix: /api/v1
    resource: AppBundle\Controller\Skills\Resources\ResourceVotes\CreateController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
