services:
    app.repository.skill:
        class: Infrastructure\ODM\Repository\SkillsRepository
        arguments: ['@doctrine.odm.mongodb.document_manager']
    app.use_case.add_skill:
        class: Domain\UseCase\AddSkill
        arguments: ['@app.repository.skill', '@slugify']
    app.use_case.list_skills:
        class: Domain\UseCase\ListSkills
        arguments: ['@app.repository.skill']
    app.use_case.remove_skill:
        class: Domain\UseCase\RemoveSkill
        arguments: ['@app.repository.skill']
    app.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                version: 'latest'
                region: "eu-west-1"
                credentials:
                    key: "%aws_s3_key%"
                    secret: "%aws_s3_secret%"
