Domain\Model\Resource:
    type: embeddedDocument
    fields:
        id:
            type: string
            id: true
            strategy: NONE

        type:
            type: string
        url:
            type: string
        description:
            type: string
        authorId:
            type: string
